#!/usr/bin/env python3
"""
=============================================================================
Lab Log Analyzer & Detection Engine
=============================================================================
Reads logs generated by the lab and applies detection rules to identify:
  1. SSH brute-force attacks
  2. Credential stuffing / password spray
  3. C2 heartbeat / beaconing
  4. Lateral movement (east-west SSH)
  5. Honeypot hits
  6. Network scanning

Each detection rule explains:
  - What it looks for
  - Why this pattern is suspicious
  - What a defender would do next (response guidance)

Usage:
  python3 analyzer.py               — analyze and show alerts
  python3 analyzer.py --live        — tail logs, alert in real time
  python3 analyzer.py --report      — full summary report
  python3 analyzer.py --rules       — list all detection rules
=============================================================================
"""

import re
import json
import sys
import time
import os
import argparse
from collections import defaultdict, Counter
from datetime import datetime, timedelta
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

LOG_DIR = Path("/var/log/lab")
AUTH_LOG = LOG_DIR / "auth.log"
HONEYPOT_LOG = LOG_DIR / "honeypot_events.jsonl"

# Alert severity levels
CRITICAL = "CRITICAL"
HIGH     = "HIGH"
MEDIUM   = "MEDIUM"
LOW      = "LOW"
INFO     = "INFO"

# Thresholds (tunable)
BRUTE_FORCE_THRESHOLD   = 5    # failed attempts in window = brute-force
SPRAY_THRESHOLD         = 3    # same password, many users = spray
SCAN_PORT_THRESHOLD     = 5    # connections to >5 ports = scan
BEACON_REGULARITY_SEC   = 5    # max variance in beacon interval (seconds)
LATERAL_MOVE_THRESHOLD  = 2    # internal-to-internal SSH attempts

# CIDR ranges for east-west detection (attack_net excluded — attacker lives there)
INTERNAL_NETS = ["10.10.", "10.20.", "10.30.", "192.168.100."]


# ---------------------------------------------------------------------------
# Log parsers
# ---------------------------------------------------------------------------

FAILED_RE = re.compile(
    r"Failed password for (?:invalid user )?(?P<user>\S+) from (?P<src_ip>[\d.]+) port (?P<src_port>\d+)"
)
ACCEPT_RE = re.compile(
    r"Accepted password for (?P<user>\S+) from (?P<src_ip>[\d.]+) port (?P<src_port>\d+)"
)
INVALID_RE = re.compile(
    r"Invalid user (?P<user>\S+) from (?P<src_ip>[\d.]+)"
)
DISCONNECT_RE = re.compile(
    r"(?P<ts>\w+ +\d+ [\d:]+) .*sshd.* "
    r"Received disconnect from (?P<src_ip>[\d.]+) port (?P<src_port>\d+)"
)
CONN_OPEN_RE = re.compile(
    r"(?P<ts>\w+ +\d+ [\d:]+) .*sshd.* "
    r"Connection from (?P<src_ip>[\d.]+) port (?P<src_port>\d+)"
)


def parse_auth_log(path: Path) -> list[dict]:
    """Parse /var/log/auth.log into structured events."""
    events = []
    if not path.exists():
        return events
    with open(path) as f:
        for line in f:
            for pattern, etype in [
                (FAILED_RE,     "ssh_failed"),
                (ACCEPT_RE,     "ssh_accepted"),
                (INVALID_RE,    "ssh_invalid_user"),
                (DISCONNECT_RE, "ssh_disconnect"),
                (CONN_OPEN_RE,  "ssh_connection"),
            ]:
                m = pattern.search(line)
                if m:
                    ev = {"type": etype, "raw": line.strip(), **m.groupdict()}
                    events.append(ev)
                    break
    return events


def parse_honeypot_log(path: Path) -> list[dict]:
    """Parse structured honeypot JSONL log."""
    events = []
    if not path.exists():
        return events
    with open(path) as f:
        for line in f:
            try:
                events.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    return events


# ---------------------------------------------------------------------------
# Alert class
# ---------------------------------------------------------------------------

class Alert:
    def __init__(self, severity, rule_id, title, description,
                 evidence, response, source_ip=None):
        self.severity = severity
        self.rule_id = rule_id
        self.title = title
        self.description = description
        self.evidence = evidence
        self.response = response
        self.source_ip = source_ip
        self.ts = datetime.utcnow().isoformat()

    def __str__(self):
        bar = "=" * 60
        sev_icon = {
            CRITICAL: "[!!!]", HIGH: "[!]", MEDIUM: "[~]", LOW: "[-]", INFO: "[i]"
        }.get(self.severity, "[?]")
        lines = [
            f"\n{bar}",
            f"{sev_icon} {self.severity} — {self.title}",
            f"Rule: {self.rule_id}   Time: {self.ts}",
            f"{bar}",
            f"  What:     {self.description}",
            f"  Evidence: {self.evidence}",
            f"  Respond:  {self.response}",
        ]
        if self.source_ip:
            lines.append(f"  Source:   {self.source_ip}")
        return "\n".join(lines)

    def to_dict(self):
        return {
            "ts": self.ts, "severity": self.severity,
            "rule_id": self.rule_id, "title": self.title,
            "source_ip": self.source_ip, "evidence": self.evidence,
        }


# ---------------------------------------------------------------------------
# Detection rules
# ---------------------------------------------------------------------------

def rule_ssh_brute_force(events: list) -> list[Alert]:
    """
    RULE: SSH-001 — SSH Brute-Force Attack
    
    Logic: Count failed auth attempts per source IP within a rolling window.
    If any IP exceeds BRUTE_FORCE_THRESHOLD failures, fire an alert.
    
    Why it works: Legitimate users mistype passwords 1-2 times at most.
    Dozens of failures from the same IP in seconds = automated attack.
    
    False positive risk: LOW. Legitimate users rarely fail >5 times.
    """
    alerts = []
    failed_by_ip = defaultdict(list)

    for ev in events:
        if ev["type"] == "ssh_failed":
            failed_by_ip[ev["src_ip"]].append(ev)

    for ip, failures in failed_by_ip.items():
        if len(failures) >= BRUTE_FORCE_THRESHOLD:
            users_tried = set(f.get("user", "?") for f in failures)
            alerts.append(Alert(
                severity=HIGH if len(failures) < 20 else CRITICAL,
                rule_id="SSH-001",
                title="SSH Brute-Force Attack Detected",
                description=(
                    f"Source IP {ip} made {len(failures)} failed SSH login "
                    f"attempts, targeting {len(users_tried)} usernames."
                ),
                evidence=(
                    f"{len(failures)} failures from {ip}. "
                    f"Usernames tried: {', '.join(list(users_tried)[:5])}"
                ),
                response=(
                    "1. Block source IP: iptables -A INPUT -s {ip} -j DROP  "
                    "2. Check if any attempt succeeded (look for ssh_accepted)  "
                    "3. Install fail2ban to automate this response  "
                    "4. Disable PasswordAuthentication in sshd_config"
                ),
                source_ip=ip,
            ))
    return alerts


def rule_password_spray(events: list) -> list[Alert]:
    """
    RULE: SSH-002 — Password Spray Attack
    
    Logic: A spray attack uses ONE password against MANY usernames,
    unlike brute-force which tries many passwords against one username.
    Detect by finding IPs that try the same password across many users.
    
    Why it's different: Spraying avoids account lockout by staying under
    the per-account threshold. It's harder to detect than brute-force.
    """
    alerts = []
    ip_users = defaultdict(set)
    ip_failures = defaultdict(int)

    for ev in events:
        if ev["type"] == "ssh_failed":
            # Only count ssh_failed — sshd logs both "Invalid user X" and
            # "Failed password for invalid user X" for non-existent accounts,
            # so including ssh_invalid_user would double-count those attempts.
            ip = ev.get("src_ip", "?")
            user = ev.get("user", "?")
            ip_users[ip].add(user)
            ip_failures[ip] += 1

    for ip, users in ip_users.items():
        if len(users) >= SPRAY_THRESHOLD and ip_failures[ip] <= len(users) * 3:
            alerts.append(Alert(
                severity=HIGH,
                rule_id="SSH-002",
                title="Password Spray Attack Detected",
                description=(
                    f"Source IP {ip} attempted SSH login against "
                    f"{len(users)} different usernames — typical spray pattern."
                ),
                evidence=f"Users targeted: {', '.join(list(users)[:8])}",
                response=(
                    "1. Block source IP  "
                    "2. Audit all targeted accounts for compromise  "
                    "3. Enforce password complexity / MFA  "
                    "4. Monitor for any successful logins from this IP"
                ),
                source_ip=ip,
            ))
    return alerts


def rule_successful_auth_from_suspicious(events: list) -> list[Alert]:
    """
    RULE: SSH-003 — Successful Login After Multiple Failures
    
    Logic: Find IPs that had many failures AND at least one success.
    This is the smoking gun — the brute-force WORKED.
    
    Why critical: This means an attacker now has a valid shell.
    Response must include immediate containment.
    """
    alerts = []
    ip_failed = Counter()
    ip_success = defaultdict(list)

    for ev in events:
        if ev["type"] == "ssh_failed":
            ip_failed[ev["src_ip"]] += 1
        elif ev["type"] == "ssh_accepted":
            ip_success[ev["src_ip"]].append(ev)

    for ip, successes in ip_success.items():
        failures_before = ip_failed.get(ip, 0)
        if failures_before >= 3:
            users = set(ev.get("user", "?") for ev in successes)
            alerts.append(Alert(
                severity=CRITICAL,
                rule_id="SSH-003",
                title="Successful Login After Brute-Force",
                description=(
                    f"IP {ip} succeeded after {failures_before} failures. "
                    f"User(s) {', '.join(users)} logged in. "
                    f"SYSTEM MAY BE COMPROMISED."
                ),
                evidence=(
                    f"Accepted: user(s)={', '.join(users)} from={ip}. "
                    f"Prior failures: {failures_before}. "
                    f"Successful logins: {len(successes)}"
                ),
                response=(
                    "IMMEDIATE ACTION:  "
                    "1. Kill active session: pkill -u {user}  "
                    "2. Lock account: passwd -l {user}  "
                    "3. Block IP: iptables -A INPUT -s {ip} -j DROP  "
                    "4. Check for persistence: crontab -l, ~/.bashrc, /etc/rc.local  "
                    "5. Review all commands run by this user: last, history"
                ),
                source_ip=ip,
            ))
    return alerts


def rule_lateral_movement(events: list) -> list[Alert]:
    """
    RULE: LATERAL-001 — East-West SSH (Lateral Movement)
    
    Logic: SSH connections originating FROM an internal IP to another
    internal IP are suspicious — legitimate admin SSH usually comes
    from outside (jump hosts) or from management networks only.
    
    Why it matters: Internal-to-internal SSH is the primary lateral
    movement technique after initial compromise.
    """
    alerts = []
    internal_src_conns = defaultdict(list)

    for ev in events:
        if ev["type"] in ("ssh_failed", "ssh_accepted"):
            src = ev.get("src_ip", "")
            is_internal = any(src.startswith(n) for n in INTERNAL_NETS)
            if is_internal:
                internal_src_conns[src].append(ev)

    for src_ip, conns in internal_src_conns.items():
        if len(conns) >= LATERAL_MOVE_THRESHOLD:
            users = set(c.get("user", "?") for c in conns)
            alerts.append(Alert(
                severity=HIGH,
                rule_id="LATERAL-001",
                title="Lateral Movement Detected (East-West SSH)",
                description=(
                    f"Internal host {src_ip} is initiating SSH connections "
                    f"to other hosts — typical pivot/lateral movement pattern."
                ),
                evidence=(
                    f"{len(conns)} SSH attempts from internal IP {src_ip}. "
                    f"Accounts targeted: {', '.join(list(users)[:5])}"
                ),
                response=(
                    "1. Investigate host {src_ip} — may be compromised pivot  "
                    "2. Block east-west SSH: iptables -A FORWARD -p tcp --dport 22 -j DROP  "
                    "3. Check what accounts this host has been accessing  "
                    "4. Isolate host: docker network disconnect ... victim1"
                ),
                source_ip=src_ip,
            ))
    return alerts


def rule_honeypot_hit(honeypot_events: list) -> list[Alert]:
    """
    RULE: HONEYPOT-001 — Honeypot Interaction
    
    Logic: ANY connection to the honeypot is suspicious.
    No legitimate user should ever connect to 10.10.0.50.
    Zero false positives by design.
    
    This is one of the highest-confidence detection signals available.
    """
    alerts = []
    hits = [e for e in honeypot_events
            if e.get("role") == "honeypot"
            and e.get("event") in ("ssh_failed_auth", "ssh_successful_auth", "ssh_invalid_user")]

    if not hits:
        return alerts

    sources = Counter(h.get("src_ip") for h in hits)
    for src_ip, count in sources.items():
        severity = CRITICAL if any(
            h.get("event") == "ssh_successful_auth" and h.get("src_ip") == src_ip
            for h in hits
        ) else HIGH

        alerts.append(Alert(
            severity=severity,
            rule_id="HONEYPOT-001",
            title="Honeypot Hit — Attacker Detected in Internal Network",
            description=(
                f"Source {src_ip} interacted with the honeypot at 10.10.0.50 "
                f"({count} times). This host SHOULD NOT EXIST in legitimate traffic. "
                f"Attacker has successfully pivoted into Network B."
            ),
            evidence=f"{count} connections to honeypot from {src_ip}",
            response=(
                "1. Source has pivoted into internal network — trace the pivot path  "
                "2. Find which Network A host was used as pivot  "
                "3. Isolate the pivot host immediately  "
                "4. Review all honeypot interaction details in /var/log/lab/honeypot_events.jsonl"
            ),
            source_ip=src_ip,
        ))
    return alerts


def rule_c2_beaconing(honeypot_events: list) -> list[Alert]:
    """
    RULE: C2-001 — C2 Heartbeat / Beaconing
    
    Logic: Look for structured beacon events in the honeypot log.
    In a real environment, you'd look for regular-interval HTTP connections
    to unusual IPs in firewall/proxy logs.
    
    The beacon interval regularity (jitter analysis) is the key signal —
    human traffic is irregular, bot beacons are suspiciously regular.
    """
    alerts = []
    beacon_events = [
        e for e in honeypot_events
        if e.get("event") in ("HEARTBEAT", "REGISTER", "STATUS", "BEACON SENT")
        or "beacon" in str(e.get("event", "")).lower()
    ]

    if len(beacon_events) >= 3:
        bot_ids = set(e.get("bot_id", "?") for e in beacon_events)
        src_ips = set(e.get("ip", e.get("src_ip", "?")) for e in beacon_events)
        alerts.append(Alert(
            severity=HIGH,
            rule_id="C2-001",
            title="C2 Beaconing Activity Detected",
            description=(
                f"Detected {len(beacon_events)} C2 beacon events. "
                f"Bot IDs: {bot_ids}. "
                f"This indicates active botnet communication."
            ),
            evidence=(
                f"{len(beacon_events)} beacon events from {src_ips}. "
                f"Look for regular-interval HTTP POST to port 8888."
            ),
            response=(
                "1. Block C2 server IP in firewall  "
                "2. Identify all beaconing hosts (bot_id field)  "
                "3. Isolate infected hosts from network  "
                "4. Look for persistence mechanisms on infected hosts  "
                "5. Use the beacon interval to write an IDS rule (Snort/Suricata)"
            ),
        ))
    return alerts


# ---------------------------------------------------------------------------
# Detection rules catalog (for --rules flag)
# ---------------------------------------------------------------------------

RULES_CATALOG = [
    {
        "id": "SSH-001", "severity": HIGH,
        "name": "SSH Brute-Force Attack",
        "detects": f">{BRUTE_FORCE_THRESHOLD} failed logins from same IP",
        "log_source": "auth.log",
        "key_field": "src_ip failure count",
    },
    {
        "id": "SSH-002", "severity": HIGH,
        "name": "Password Spray Attack",
        "detects": f"Same IP targeting >{SPRAY_THRESHOLD} different usernames",
        "log_source": "auth.log",
        "key_field": "unique usernames per IP",
    },
    {
        "id": "SSH-003", "severity": CRITICAL,
        "name": "Successful Brute-Force Login",
        "detects": "Accepted login after multiple failures",
        "log_source": "auth.log",
        "key_field": "accepted_after_failures",
    },
    {
        "id": "LATERAL-001", "severity": HIGH,
        "name": "East-West SSH (Lateral Movement)",
        "detects": "Internal-to-internal SSH connection attempts",
        "log_source": "auth.log",
        "key_field": "src_ip in internal range",
    },
    {
        "id": "HONEYPOT-001", "severity": CRITICAL,
        "name": "Honeypot Interaction",
        "detects": "Any connection to honeypot IP (10.10.0.50)",
        "log_source": "honeypot_events.jsonl",
        "key_field": "role=honeypot",
    },
    {
        "id": "C2-001", "severity": HIGH,
        "name": "C2 Beaconing",
        "detects": "Regular-interval beacon events",
        "log_source": "honeypot_events.jsonl",
        "key_field": "event=HEARTBEAT",
    },
]


# ---------------------------------------------------------------------------
# Main analysis engine
# ---------------------------------------------------------------------------

def run_analysis(verbose: bool = True) -> list[Alert]:
    print("\n[analyzer] Loading logs...")
    auth_events = parse_auth_log(AUTH_LOG)
    honeypot_events = parse_honeypot_log(HONEYPOT_LOG)

    print(f"[analyzer] Parsed {len(auth_events)} auth events, "
          f"{len(honeypot_events)} honeypot events")

    all_alerts = []
    rules = [
        ("SSH-001 Brute Force",        lambda: rule_ssh_brute_force(auth_events)),
        ("SSH-002 Password Spray",      lambda: rule_password_spray(auth_events)),
        ("SSH-003 Successful BF Login", lambda: rule_successful_auth_from_suspicious(auth_events)),
        ("LATERAL-001 East-West SSH",   lambda: rule_lateral_movement(auth_events)),
        ("HONEYPOT-001 Honeypot Hit",   lambda: rule_honeypot_hit(honeypot_events)),
        ("C2-001 Beaconing",            lambda: rule_c2_beaconing(honeypot_events)),
    ]

    for rule_name, rule_fn in rules:
        alerts = rule_fn()
        if alerts and verbose:
            for a in alerts:
                print(a)
        all_alerts.extend(alerts)

    return all_alerts


def print_report(alerts: list[Alert]):
    print("\n" + "=" * 60)
    print(" DETECTION REPORT SUMMARY")
    print("=" * 60)

    by_sev = Counter(a.severity for a in alerts)
    print(f"\n  Total alerts:    {len(alerts)}")
    for sev in [CRITICAL, HIGH, MEDIUM, LOW, INFO]:
        count = by_sev.get(sev, 0)
        if count:
            print(f"  {sev:10s}:  {count}")

    if not alerts:
        print("\n  No alerts generated.")
        print("  Run the simulator first: docker exec attacker python3 /lab/simulator.py botnet")
    else:
        print("\n  Triggered rules:")
        for a in alerts:
            print(f"    [{a.severity:8s}] {a.rule_id} — {a.title}")

    print("\n" + "=" * 60)


def live_monitor():
    """Watch logs in real time and alert on new events."""
    print("[analyzer] Live monitoring mode — press Ctrl+C to stop\n")
    seen_lines = set()
    while True:
        alerts = run_analysis(verbose=False)
        for a in alerts:
            key = f"{a.rule_id}:{a.source_ip}"
            if key not in seen_lines:
                print(a)
                seen_lines.add(key)
        time.sleep(5)


def list_rules():
    print("\n Detection Rules Catalog\n")
    print(f"  {'ID':<16} {'SEVERITY':<10} {'NAME':<35} {'DETECTS'}")
    print("  " + "-" * 90)
    for r in RULES_CATALOG:
        print(f"  {r['id']:<16} {r['severity']:<10} {r['name']:<35} {r['detects']}")
    print()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Lab Log Analyzer — detection rules for SSH botnet lab"
    )
    parser.add_argument("--live",   action="store_true", help="Real-time monitoring")
    parser.add_argument("--report", action="store_true", help="Print summary report")
    parser.add_argument("--rules",  action="store_true", help="List detection rules")
    args = parser.parse_args()

    if args.rules:
        list_rules()
        return

    if args.live:
        live_monitor()
        return

    alerts = run_analysis(verbose=True)

    if args.report:
        print_report(alerts)


if __name__ == "__main__":
    main()
